### ISSUE TITLE
[Urgent] Download script: poor documentation, cannot run!

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_311#16]
**Improvements to documentation required:**

1. Documentation of script should give example of usage with the URL and file path/name used for the project.
2. Documentation should indicate the split used for test/train data.

**Recommended improvement if time allows**

While trying to figure out (1) I ran into an error. When navigating to the [link in your README](http://archive.ics.uci.edu/ml/datasets/Wine+Quality) it is possible to land on [this page](http://www3.dsi.uminho.pt/pcortez/wine/) and get the url `http://www3.dsi.uminho.pt/pcortez/wine/winequality.zip`. This results in the error message:

> ValueError: ('Multiple files found in compressed zip file %s', "['winequality/winequality-names.txt', 'winequality/winequality-names.txt.bak', 'winequality/winequality-red.csv', 'winequality/winequality-white.csv']")

Consider adding a test to account for this type of error. However, if documentation is clear, this is less likely.

**Comment by HanyingZhang** [comment]
Thank you Kate! We used the URL of `https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv`. We will modify the script to cover this sort of problem.

**Comment by ksedivyhaley** [comment]
Thanks! Runs fine so I'll note this as a documentation issue not a broken script. Modifying the main issue post above to reflect fixes that should still be implemented.
