### ISSUE TITLE
Group Meeting Appointment

### ISSUE THREAD

**Issue by chuusan** [UBC-MDS/DSCI_522_GROUP_311#2]
Folks,

I booked a study space for tomorrow's group meeting.

**Locaton: MAA Library - Group Study Rooms317 - Group Study
Time: 3:30pm - 5:30pm Friday, January 17, 2020.**

Please arrive on time, thank you!

Best,

Kirk Zhong

**Comment by HanyingZhang** [comment]
Thanks Kirk!

**Comment by taohuang-ubc** [comment]
resolve #2
