### ISSUE TITLE
Visualization feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_311#33]
- Figure 3 isn't very effective.
- For bar graphs (Figure 2), sort bars by height
- Larger text
- Use more polished labels
  - lower number of decimal points, especially on n_features_to_select (integer)
  - Underscores are great for code - figure labels should have spaces

**Comment by HanyingZhang** [comment]
Thank you Kate for all these suggestions😃! We'll look into the problems and fix them.

**Comment by taohuang-ubc** [comment]
This issue is fixed by by my last pull request.  hanying, sorry I forget to mention, can you close this one ?

**Comment by taohuang-ubc** [comment]
@HanyingZhang
