### ISSUE TITLE
Please check new `makefile`

### ISSUE THREAD

**Issue by HanyingZhang** [UBC-MDS/DSCI_522_GROUP_311#45]
Hi✋! I have pull request the `Makefile`. Please check if this also works for you! 
I couldn't use Rstudio terminal to run `make` so I used Git bash instead for now. But it would be better if at least one of us can test the validness of this on Rstudio terminal I guess. So please check 😀!

**Comment by taohuang-ubc** [comment]
makefile works ok, I will close #45

**Comment by taohuang-ubc** [comment]
resolve #45
