### ISSUE TITLE
Milestone 3: Report feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_311#53]
**Reasoning**

- While generally, your description of your method is strong, you could indicate why you decided to work with a linear regression algorithm as opposed to another type of model.
  - Good explanation of how sklearn picks top features
- **Most important:** Description of Figure 3 is not very accurate - the model under-estimates grade 8 wine as you say, but it *over*-estimates grade 4 wine. It also doesn't seem to make good predictions for grade 7.
- Your critique (discussion) is pretty good. I'd like to see a comment on the variation you're seeing in Fig 3 - how does that relate to how good your model is?
- You have one good idea for future directions - any more?

**Writing:**  Minor grammatical errors, eg:

  - "is mainly relying on qualified experts" > "mainly relies on"
  - "data used in this project is obtain from" > "is obtained from"
  - "Reragding" > "regarding"
  - "is a reason model to choose" > "is a reasonable model"

**Mechanics:** Still need to cite an external source (you link to one but make sure to include it in your reference list)

**Comment by HanyingZhang** [comment]
Hi Kate! Thank you for the feedback. I checked the reference list and I think the external source was included as: 
```
@article{cortez2009modeling,
  title={Modeling wine preferences by data mining from physicochemical properties},
  author={Cortez, Paulo and Cerdeira, Ant{\'o}nio and Almeida, Fernando and Matos, Telmo and Reis, Jos{\'e}},
  journal={Decision Support Systems},
  volume={47},
  number={4},
  pages={547--553},
  year={2009},
  publisher={Elsevier}
}
```
And it also showed up in the reference section in the report: 
![image](https://user-images.githubusercontent.com/35021819/74073464-49905b80-49bf-11ea-81f8-b61179fe8623.png)  
This is the link to this source:  
https://www.sciencedirect.com/science/article/pii/S0167923609001377?via%3Dihub

**Comment by ksedivyhaley** [comment]
Thanks for the clarification, I mistook that for your data source.

On that note, your References section should also include your data source, as indicated on this page: http://archive.ics.uci.edu/ml/datasets/Wine+Quality

Paulo Cortez, University of Minho, Guimarães, Portugal, http://www3.dsi.uminho.pt/pcortez
A. Cerdeira, F. Almeida, T. Matos and J. Reis, Viticulture Commission of the Vinho Verde Region(CVRVV), Porto, Portugal
@2009

**Comment by HanyingZhang** [comment]
Thanks Kate 😃!
