### ISSUE TITLE
Question about dataset url

### ISSUE THREAD

**Issue by HanyingZhang** [UBC-MDS/DSCI_522_GROUP_311#6]
Hi team! I have created the script that downloads the data. 

I noticed that we used data from Kaggle now, but I haven't figured out how to download data through Kaggle url. For now I am using the old url("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv").

According to the description on Kaggle, I think the content of these two data should be the same. So I wonder if it is okay to use the UCI one?

**Comment by taohuang-ubc** [comment]
@HanyingZhang , the reason why I switched to the Kaggle red wine data set is that: the UCI data is not actually 'comma sepaerated', all data is in ONE column, it is really messy and not useful. I think there should be a way to download from Kaggle, which provides a clean format. I am looking at this issue.

**Comment by taohuang-ubc** [comment]
@HanyingZhang If you take a look at the file downloaded from UCI, you will get what I meant.

**Comment by taohuang-ubc** [comment]
since the datasets are the sane, should be fine.
