### ISSUE TITLE
About closing the pr and some suggestions (my apologies!)

### ISSUE THREAD

**Issue by HanyingZhang** [UBC-MDS/DSCI_522_GROUP_311#63]
Hi Kirk, thanks a lot! But I'll have to close your pull request because I saw conflicts in your commit. Please fetch and merge the upstream before you continue to work. 

I am so sorry that I forgot to post an issue about what was done. Sorry to trouble you because my lack of communication. My bad 😭 I read your commits, and I think the viz part and the result part of the report has already been fixed in some content. After your fork is even with the upstream, you'll be able to see these changes, and you can work on that version then. 

Several things to be noted: 
- I tried to improve the visualizations based on the feedback we received. Most problems seem to be fixed now. But Firas mentioned that it would be better if we could **increase the size of the axis text**. However, I couldn't find a way to work this out. So if you are still working on the viz part, you can start from that. Though I feel the current size looks fine to me. You don't have to spend much time on that. 
- **Important**: please **never** directly modify the markdown file. I saw you made a lot of improvements to our report. 😍👍! So if you are working on the report again (sorry my mistake made you do these all again), please work on the **RMarkdown** file directly. And when you feel everything's done, use `make all` to update everything. (But if you only modify the report file in the whole repository, it might be faster to just knit the Rmd.) Then, make sure you also push all the updated files (including markdown and html) to github.

Sorry again about the mess. I will also post an issue of the above content. And you can always post an issue to communicate with us. Don't repeat my mistake 😭.

**Comment by chuusan** [comment]
Thanks Hanying!
